spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.103/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  #freemarker模板引擎
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxd52f0c3beb069d94
  mpAppSecret: b2495bca0377150de9fb7c55915b3ab9
